version: "3.9"
services:
  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    volumes:
      - ${PWD}/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
  pgadmin:
    container_name: "pgadmin"
    image: "dpage/pgadmin4:latest"
    ports:
      - "8080:80"
    volumes:
      - ${PWD}/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
